import { Inter } from "next/font/google"
import { ThemeProvider } from "next-themes"
import "./globals.css"

import { Footer } from "@/components/Footer"
import { PopupWidget } from "@/components/PopupWidget"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "InfoSathi",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <div>{children}</div>
          <Footer />
          <PopupWidget />
        </ThemeProvider>
      </body>
    </html>
  )
}
